language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t react-app -f Dockerfile ./

script:
<<<<<<< HEAD
  - docker run -e CI=true react-app npm run test
=======
  - docker run -e CI=true react-app npm run test -- --watchAll=false
>>>>>>> 312124eb22b952308cfb321e7382a5f069e3b8c2

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "react-app"
  env: "ReactApp-env"
  bucket_name: "elasticbeanstalk-us-east-2-304355919383"
  bucket_path: "react-app"
  on:
    branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
<<<<<<< HEAD
=======
    
>>>>>>> 312124eb22b952308cfb321e7382a5f069e3b8c2
